language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Bionic Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      dist: bionic
      before_install:
        - curl -L https://ziglang.org/download/0.6.0/zig-linux-x86_64-0.6.0.tar.xz | tar -xJf -
      env:
        - PATH="$(pwd)/zig-linux-x86_64-0.6.0:$PATH"
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - brew install zig
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - cp /c/Python38/python.exe /c/Python38/python3.exe
        - python -m pip install --upgrade pip
        - choco install zig --version 0.6.0
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

git:
  autocrlf: input
  depth: false

install:
 - git fetch --tags
 - python ./get-toolchain.py

script:
 - source .github/travis-pretty.inc.sh
 - ./.github/tests.sh
